version: "2.0"

services:
  app:
    container_name: app-dev
    image: app-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/walmart/src
    ports:
      - 3000:3000
